[package]
name = "spot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.12"
clap = { version = "4.2.1", features = ["env", "derive"] }
reqwest = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0.159", features = ["serde_derive"] }
tokio = { version = "1.27.0", features = ["full"] }
uuid = { version = "1.3.0", features = ["v4"] }
