version: "3.8"
services:
  beam-proxy:
    image: samply/beam-proxy:develop
    ports:
      - 8081:8081
    environment:
      BROKER_URL: https://${BROKER_ID}
      PROXY_ID: ${SITE_ID}.${BROKER_ID}
      APP_spot_KEY: ${BEAM_APP_SECRET}
      PRIVKEY_FILE: /run/secrets/proxy.pem
      ROOTCERT_FILE: /conf/root.crt.pem
      ALL_PROXY: ${http_proxy}
      RUST_LOG: "debug"
    secrets:
      - proxy.pem
    volumes:
      - ./root.crt.pem:/conf/root.crt.pem:ro

secrets:
  proxy.pem:
    file: /etc/lens/pki/${SITE_ID}.priv.pem
