
name: Docker

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

jobs:
  docker:
    # This workflow defines how a maven package is built, tested and published.
    # Visit: https://github.com/samply/github-workflows/blob/develop/.github/workflows/docker-ci.yml, for more information
    uses: samply/github-workflows/.github/workflows/rust.yml@main
    with:
      # For information on these variables, please refer to https://github.com/samply/github-workflows/tree/main/.github/workflows/rust.yml
      # Docker Hub name will be {image-prefix}{component}
      image-prefix: "samply/"
      components: '[ "rustyspot" ]'
      #architectures: '[ "amd64" ]'
      push-to: ${{ (github.ref_protected == true || github.event_name == 'workflow_dispatch') && 'dockerhub' || 'ghcr' }}
    # This passes the secrets from calling workflow to the called workflow
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
